#!/bin/tcsh -f

set nonomatch


set ShapeDir = /work/maria5/EBDS_CIVILITY/LongitudinalConnectome_PostRegError/SubCortical_Processing/SALT

#echo $2

set fterm = "T1_SkullStripped_scaled_label.nrrd"

if ( $2 == 0 ) then
	# Conte 1 and 2 (option 0)
	set DataDir  = /dichter/AutoSeg_Rerun_CONTE1and2/Data
else if ( $2 == 1 ) then
	# Conte 4 and 6 (option 1)
	set DataDir  = /Human/conte_projects/CONTE_NEO/AUTOSEG_4-6year_T1andMultiAtlas/Data
else if ($2 == 2) then
	# Twin 1 and 2 (option 2)
	set DataDir  = /Human2/CONTE2/TWINS-SubCort/Data
	set fterm = "T1_regAtlas-SkullStripped_label.nrrd"
else
	# Twin 4 and 6 (option 3 )
	set DataDir  = /Human/twin-gilmore/AUTOSEG_4-6year_T1andMultiAtlas/Data
	
endif

#echo $DataDir

set ShapeAnalysisModuleCmd = /tools/bin_linux64/ShapeAnalysisModule

#set BuildDir = /work/mahmoudm/Subcortical_Processing/MapThicknessToSpharmSurface/build

#Modify for Putamen and GP 
#set Labels     = (1    2    3     4     5      6      	40    	41)
#set LabelNames = (AmyL AmyR CaudL CaudR HippoL HippoR ThalL ThalR)
# checked the labels in ITK SNAP)
set Labels = (7   8   9    10)
set LabelNames = (GPL GPR PutL PutR)
#set Labels = (9 10)
#set LabelNames = (PutL PutR)

set TemplateDir = $ShapeDir/Template
set ProcessDir  = $ShapeDir/processing

set counter = 0
set maxcounter = $#Labels

# I don't know where these files were from- however he uses it to label the output surface
set ParaPhiFile = $ProcessDir/paraPhi_l10.txt
set ParaThetaFile = $ProcessDir/paraTheta_l10.txt
set CheckerFile = $ProcessDir/checkerboardRGB_l10.txt

while ($counter < $maxcounter)
    echo $counter

    @ counter = $counter + 1
    set index = $counter

    #echo doing $Labels[$index] ':' $LabelNames[$index]
	# NOTE check why using this Template Mean etc and if we need it 
    set TemplateProc = $TemplateDir/$LabelNames[$index]/Template_Mean.vtk
    set TemplateCoef = $TemplateDir/$LabelNames[$index]/Template_*_ellalign.coef

	foreach idx (`cat $1`)
		set case = $DataDir/$idx/AutoSegTissue_1year_v2-MultiAtlas/fused-labels/$idx-$fterm
		#echo $case

		set OutputDir = $case:h:h/SALT
            #echo $OutputDir

		if (! -e $OutputDir) then
		mkdir $OutputDir
	        endif 

		#if ($2 == 3) then
		#rm $OutputDir/*-T1_regAtlas-SkullStripped_label_$LabelNames[$index]_*.vtk
		#rm $OutputDir/*-T1_regAtlas-SkullStripped_label_$LabelNames[$index]_*.coef
		#rm $OutputDir/*-T1_regAtlas-SkullStripped_label_$LabelNames[$index]_*.txt
		#rm $OutputDir/*-T1_regAtlas-SkullStripped_label_$LabelNames[$index]_*.csv
		#endif
	    set PPtarget = $OutputDir/$case:t:r_$LabelNames[$index]_pp.nrrd

	    if (! -e $PPtarget) then
			#echo `date` SegPostProcessCLP $case:t $OutputDir
			SegPostProcessCLP $case $PPtarget --label $Labels[$index] --space 0.75,0.75,0.75 --rescale --verb >! $OutputDir/$LabelNames[$index]_segpostprocess.log
	    endif
  
	    set Paratarget = $PPtarget:r_para.vtk
	    set Surftarget = $PPtarget:r_surf.vtk

	    if (! -e $Paratarget) then
			#echo `date` GenParaMeshCLP $Paratarget
			GenParaMeshCLP --EulerFile --outEulerName $PPtarget:r_Euler.txt --iter 500 --label 1 $PPtarget $Paratarget $Surftarget --verb >! $OutputDir/$LabelNames[$index]_genparamesh.log
            endif

#Write a list of errors if unsuccessful
if (! -e $Surftarget) then 
echo ERROR Calculating $Surftarget
echo ""$Surftarget"" >> "/work/maria5/EBDS_CIVILITY/LongitudinalConnectome_PostRegError/SubCortical_Processing/SALT/processing/RunFullDataset_202004/DocumentFailures/Failed_$LabelNames[$index].txt"

endif

	   
            
	    set SurfVTKtarget = $Surftarget:rSPHARM.vtk

	    if (! -e $SurfVTKtarget) then
			#echo `date` ParaToSPHARMMeshCLP $SurfVTKtarget
			ParaToSPHARMMeshCLP $Paratarget $Surftarget $Surftarget:r --subdivLevel 10 --spharmDegree 15 --flipTemplate $TemplateCoef --regTemplate $TemplateProc --flipTemplateOn --regTemplateFileOn  --phiIteration 100 --thetaIteration 100 --medialMesh --paraOut >! $OutputDir/$LabelNames[$index]_paraspharm.log 
			MeshMath $SurfVTKtarget $SurfVTKtarget -KWMtoPolyData $ParaThetaFile Theta 
			MeshMath $SurfVTKtarget $SurfVTKtarget -KWMtoPolyData $ParaPhiFile  Phi
	    endif
#Write a list of errors if unsuccessful
if (! -e $SurfVTKtarget) then 
echo ERROR Calculating $SurfVTKtarget
echo ""$SurfVTKtarget"" >> "/work/maria5/EBDS_CIVILITY/LongitudinalConnectome_PostRegError/SubCortical_Processing/SALT/processing/RunFullDataset_202004/DocumentFailures/Failed_$LabelNames[$index].txt"
else
echo SUCCESS $SurfVTKtarget Complete
endif

	end

end

exit
