#!/bin/bash



runfile="/NIRAL/work/maria5/EBDS_CIVILITY/LongitudinalConnectome_PostRegError/SubCortical_Processing/SALT/processing/RunFullDataset_202004/RunFiles_WARP/Conte1Yr/RunList_Conte1YrBatch_5.txt"

#if [ $count==3 ]
#then
#RunSPHARM-PDM_Put_and_GP_EBDS_final.script $runfile 0 
#count=0
#echo submit $runfile
#else 
Label_Combine_WARPtoDWISpace_SALTSubcorts_EBDS_final.sh $runfile 0 /NIRAL/work/maria5/EBDS_CIVILITY/LongitudinalConnectome_PostRegError/SubCortical_Processing/SALT/processing/RunFullDataset_202004/Conte_1YrTest.csv
#let count++
#echo submit $runfile
#fi 

#done