#!/bin/tcsh -f

set nonomatch

set PPtarget = $1
echo $PPtarget 

set Paratarget = $PPtarget:r_para.vtk
set Surftarget = $PPtarget:r_surf.vtk

echo Running GenParaMeshCLP	   
GenParaMeshCLP --EulerFile --outEulerName $PPtarget:r_Euler.txt --iter 500 --label 1 $PPtarget $Paratarget $Surftarget 
#--verb >! genparamesh.log
         

#Test if successful 
if (! -e $Surftarget) then 
echo ERROR Calculating $Surftarget
else 
echo SUCCESS $Surftarget Complete
	    set SurfVTKtarget = $Surftarget:rSPHARM.vtk
	   
ParaToSPHARMMeshCLP $Paratarget $Surftarget $Surftarget:r --subdivLevel 10 --spharmDegree 15 

endif

if (! -e $SurfVTKtarget) then 
echo ERROR Calculating $SurfVTKtarget
else
echo SUCCESS $SurfVTKtarget Complete
endif


exit